# Generated by Django 5.2.14 on 2026-05-07 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='creada',
            new_name='fecha_creada',
        ),
    ]
