# Generated by Django 5.2.14 on 2026-05-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_remove_tarea_completada_tarea_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Completada', 'Completada')], default='Borrador', max_length=20),
        ),
    ]
